# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: WaveCorporation.Visir
executable_name: Visir
publisher: Wave Corporation
publisher_url: https://visir.pro
display_name: Visir
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
locales:
  - en